# Generated by Django 3.2.2 on 2021-05-09 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Olimpimat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("imagem", models.ImageField(upload_to="desafio/%Y/%m/%d/")),
                ("descricao", models.TextField()),
                ("processed_descricao", models.TextField(blank=True)),
                ("regulamento", models.FileField(upload_to="desafio/%Y/%m/%d/")),
                ("cronograma", models.FileField(upload_to="desafio/%Y/%m/%d/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="Image url and path",
                        upload_to="%Y/%m/%d/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Image name",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "upload_in",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="image upload date",
                        verbose_name="Upload in",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True)),
                ("data_de_inicio", models.DateField()),
                ("data_de_termino", models.DateField()),
                ("prova", models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/")),
                (
                    "gabarito",
                    models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/"),
                ),
                ("url_cadastro", models.URLField(blank=True)),
                ("url_prova", models.URLField()),
                (
                    "resultado",
                    models.FileField(blank=True, upload_to="desafio/%Y/%m/%d/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Aberto", "A"), ("Encerrado", "B")],
                        max_length=50,
                    ),
                ),
                (
                    "edicao_olimpiada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.olimpimat",
                    ),
                ),
            ],
        ),
    ]
