# Generated by Django 3.2.2 on 2021-05-23 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_contribute_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="post title", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="post content", verbose_name="Content"),
                ),
                (
                    "posted_in",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="post publication date",
                        verbose_name="Posted in",
                    ),
                ),
                (
                    "poster",
                    models.ForeignKey(
                        help_text="post editor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
