# Generated by Django 3.2.2 on 2021-05-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Aberto", "A"), ("Encerrado", "B"), ("Agendado", "C")],
                max_length=50,
            ),
        ),
    ]
