# Generated by Django 3.2.2 on 2021-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_challenge_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="url_prova",
            field=models.URLField(blank=True),
        ),
    ]
