# Generated by Django 3.2.2 on 2021-06-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210607_0727"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpimat",
            name="tutorial",
            field=models.URLField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
