# Generated by Django 3.2.2 on 2021-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_olimpimat_tutorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpimat",
            name="regulamento_jr",
            field=models.FileField(default="", upload_to="regulamento/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="olimpimat",
            name="cronograma",
            field=models.FileField(upload_to="cronograma/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="olimpimat",
            name="imagem",
            field=models.ImageField(upload_to="imagem/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="olimpimat",
            name="regulamento",
            field=models.FileField(upload_to="regulamento/%Y/%m/%d/"),
        ),
    ]
